/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
// int printf(const char *format, ...);
// int close(int fd);
// struct hostent *gethostbyname(const char *name);
// int puts(const char *s);
// int __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// void __noreturn exit(int status);
// int strcasecmp(const char *s1, const char *s2);
// ssize_t read(int fd, void *buf, size_t nbytes);
// FILE *fopen(const char *filename, const char *modes);
// char *fgets(char *s, int n, FILE *stream);
// void bcopy(const void *src, void *dest, size_t n);
// const unsigned __int16 **__ctype_b_loc(void);
// int sprintf(char *s, const char *format, ...);
// unsigned int sleep(unsigned int seconds);
// __int64 strtol(const char *nptr, char **endptr, int base);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
// int gethostname(char *name, size_t len);
// void *memcpy(void *dest, const void *src, size_t n);
// __sighandler_t signal(int sig, __sighandler_t handler);
// int socket(int domain, int type, int protocol);
// char *getenv(const char *name);
// unsigned int alarm(unsigned int seconds);
// int *__errno_location(void);
// char *strcpy(char *dest, const char *src);
// int fprintf(FILE *stream, const char *format, ...);
// ssize_t write(int fd, const void *buf, size_t n);
// int fflush(FILE *stream);
int call_gmon_start();
void _do_global_dtors_aux();
void frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
__int64 __fastcall func4(__int64 a1, __int64 a2, int a3);
signed __int64 __fastcall fun7(__int64 a1, int a2);
int __fastcall secret_phase(__int64 a1, __int64 a2);
_DWORD *__fastcall phase_6(__int64 a1);
__int64 __fastcall phase_2(__int64 a1);
signed __int64 __fastcall phase_5(_BYTE *a1, __int64 a2);
signed __int64 __fastcall phase_1(_BYTE *a1);
__int64 __fastcall phase_4(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5);
signed __int64 __fastcall phase_3(__int64 a1);
__int64 __fastcall string_length(_BYTE *a1);
signed __int64 __fastcall strings_not_equal(_BYTE *a1, _BYTE *a2);
void __fastcall __noreturn invalid_phase(__int64 a1);
__int64 __fastcall send_msg(__int64 a1, __int64 a2);
int __fastcall phase_defused(__int64 a1, __int64 a2);
void __fastcall __noreturn explode_bomb(__int64 a1, __int64 a2);
int __fastcall read_six_numbers(__int64 a1, __int64 a2);
signed __int64 __fastcall blank_line(char *a1);
char *skip();
char *__fastcall read_line(__int64 a1, __int64 a2);
__int64 initialize_bomb();
void __noreturn sig_handler();
__int64 __fastcall init_driver(char *s); // idb
unsigned int __fastcall init_timeout(unsigned int seconds);
signed __int64 __fastcall rio_readlineb(__int64 a1, _BYTE *a2, unsigned __int64 a3);
// __int64 __usercall submitr@<rax>(char *name@<rdi>, _BYTE *a2@<rdx>, const char *a3@<rcx>, __int16 a4@<si>, __int64 a5@<r8>, _BYTE *a6@<r9>, __int64 a7, __int64 a8);
__int64 __fastcall driver_post(const char *a1, __int64 a2, __int64 a3, int a4, __int64 a5);
void __noreturn sigalrm_handler();
void _libc_csu_init(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();
// int _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

char array_3327[33] = "maduiersnfotvbylInvalid phase%s\n"; // weak
_UNKNOWN unk_40250E; // weak
char asc_402780[3] = "\r\n"; // weak
char aOk[3] = "OK"; // weak
char aErrorClientU_0[44] = "Error: Client unable to write to the server"; // weak
char aErrorClientU_2[56] = "Error: Client unable to read status message from server"; // weak
__int64 _CTOR_LIST__ = -1LL; // weak
__int64 _DTOR_LIST__[] = { -1LL }; // weak
_UNKNOWN _DTOR_END__; // weak
int bomb_id = 109; // weak
char userid[9] = "cohenm46"; // weak
char user_password[21] = "MdaIjdxpjWarokSnzSvc"; // weak
_UNKNOWN node1; // weak
_UNKNOWN n1; // weak
char *host_table = "u2"; // idb
_UNKNOWN unk_6034C8; // weak
__int64 stdin; // weak
FILE *stderr; // idb
FILE *stdout; // idb
char completed_6364; // weak
__int64 dtor_idx_6366; // weak
int num_input_strings; // weak
FILE *infile; // idb
char input_strings[]; // weak
_UNKNOWN unk_6039F0; // weak


//----- (0000000000400A60) ----------------------------------------------------
void (*init_proc())(void)
{
  call_gmon_start();
  frame_dummy();
  return _do_global_ctors_aux();
}

//----- (0000000000400C50) ----------------------------------------------------
#error "400C56: positive sp value has been found (funcsize=3)"

//----- (0000000000400C7C) ----------------------------------------------------
int call_gmon_start()
{
  int (**v0)(void); // rax@1

  v0 = &_gmon_start__;
  if ( &_gmon_start__ )
    LODWORD(v0) = _gmon_start__();
  return (unsigned __int64)v0;
}
// 604070: using guessed type int _gmon_start__(void);

//----- (0000000000400CA0) ----------------------------------------------------
void _do_global_dtors_aux()
{
  __int64 v0; // rax@2
  unsigned __int64 i; // rbx@2

  if ( !completed_6364 )
  {
    v0 = dtor_idx_6366;
    for ( i = ((&_DTOR_END__ - (_UNKNOWN *)_DTOR_LIST__) >> 3) - 1; dtor_idx_6366 < i; v0 = dtor_idx_6366 )
    {
      dtor_idx_6366 = v0 + 1;
      ((void (*)(void))_DTOR_LIST__[v0 + 1])();
    }
    completed_6364 = 1;
  }
}
// 602F98: using guessed type __int64 _DTOR_LIST__[];
// 6038D8: using guessed type char completed_6364;
// 6038E0: using guessed type __int64 dtor_idx_6366;

//----- (0000000000400D10) ----------------------------------------------------
void frame_dummy()
{
  ;
}

//----- (0000000000400D34) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  const char **v3; // rbx@1
  const char **v4; // rbp@4
  char *v5; // rdi@9
  char *v6; // rdi@9
  char *v7; // rdi@9
  char *v8; // rdi@9
  __int64 v9; // rdx@9
  __int64 v10; // rcx@9
  __int64 v11; // r8@9
  char *v12; // rdi@9
  char *v13; // rdi@9

  v3 = argv;
  if ( argc == 1 )
  {
    infile = (FILE *)stdin;
  }
  else
  {
    if ( argc != 2 )
    {
      printf("Usage: %s [<input_file>]\n", *argv, envp);
      exit(8);
    }
    v4 = argv + 1;
    argv = (const char **)"r";
    infile = fopen(*v4, "r");
    if ( !infile )
    {
      printf("%s: Error: Couldn't open %s\n", *v3, *v4);
      exit(8);
    }
  }
  initialize_bomb();
  puts("Welcome to my fiendish little bomb. You have 6 phases with");
  puts("which to blow yourself up. Have a nice day!");
  v5 = read_line((__int64)"which to blow yourself up. Have a nice day!", (__int64)argv);
  phase_1(v5);
  phase_defused((__int64)v5, (__int64)argv);
  puts("Phase 1 defused. How about the next one?");
  v6 = read_line((__int64)"Phase 1 defused. How about the next one?", (__int64)argv);
  phase_2((__int64)v6);
  phase_defused((__int64)v6, (__int64)argv);
  puts("That's number 2.  Keep going!");
  v7 = read_line((__int64)"That's number 2.  Keep going!", (__int64)argv);
  phase_3((__int64)v7);
  phase_defused((__int64)v7, (__int64)argv);
  puts("Halfway there!");
  v8 = read_line((__int64)"Halfway there!", (__int64)argv);
  phase_4((__int64)v8, (__int64)argv, v9, v10, v11);
  phase_defused((__int64)v8, (__int64)argv);
  puts("So you got that one.  Try this one.");
  v12 = read_line((__int64)"So you got that one.  Try this one.", (__int64)argv);
  phase_5(v12, (__int64)argv);
  phase_defused((__int64)v12, (__int64)argv);
  puts("Good work!  On to the next...");
  v13 = read_line((__int64)"Good work!  On to the next...", (__int64)argv);
  phase_6((__int64)v13);
  phase_defused((__int64)v13, (__int64)argv);
  return 0;
}
// 6038C0: using guessed type __int64 stdin;

//----- (0000000000400E70) ----------------------------------------------------
__int64 __fastcall func4(__int64 a1, __int64 a2, int a3)
{
  signed int v3; // ebx@1

  v3 = (a3 - (signed int)a2) / 2 + a2;
  if ( v3 <= (signed int)a1 )
  {
    if ( v3 < (signed int)a1 )
      v3 += func4(a1, (unsigned int)(v3 + 1));
  }
  else
  {
    v3 += func4(a1, a2);
  }
  return (unsigned int)v3;
}

//----- (0000000000400EA4) ----------------------------------------------------
signed __int64 __fastcall fun7(__int64 a1, int a2)
{
  signed __int64 result; // rax@1

  result = 0xFFFFFFFFLL;
  if ( a1 )
  {
    if ( *(_DWORD *)a1 <= a2 )
    {
      result = 0LL;
      if ( *(_DWORD *)a1 != a2 )
        result = (unsigned int)(2 * fun7(*(_QWORD *)(a1 + 16)) + 1);
    }
    else
    {
      result = (unsigned int)(2 * fun7(*(_QWORD *)(a1 + 8)));
    }
  }
  return result;
}

//----- (0000000000400EE0) ----------------------------------------------------
int __fastcall secret_phase(__int64 a1, __int64 a2)
{
  char *v2; // rdi@1
  int v3; // ebx@1

  v2 = read_line(a1, a2);
  v3 = strtol(v2, 0LL, 10);
  if ( (unsigned int)(v3 - 1) > 0x3E8 )
    explode_bomb((__int64)v2, 0LL);
  if ( (unsigned int)fun7((__int64)&n1, v3) != 3 )
    explode_bomb((__int64)&n1, (unsigned int)v3);
  puts("Wow! You've defused the secret stage!");
  return phase_defused((__int64)"Wow! You've defused the secret stage!", (unsigned int)v3);
}

//----- (0000000000400F30) ----------------------------------------------------
_DWORD *__fastcall phase_6(__int64 a1)
{
  int *v1; // rbp@1
  signed int v2; // er12@1
  signed int v3; // ebx@5
  unsigned __int64 v4; // rbx@10
  _QWORD *v5; // rdx@11
  signed int v6; // eax@11
  int v7; // ecx@13
  __int64 v8; // rbx@15
  __int64 v9; // rax@15
  __int64 v10; // rdx@15
  __int64 v11; // rax@15
  __int64 v12; // rdx@15
  __int64 v13; // rax@15
  int v14; // ebp@15
  _DWORD *result; // rax@16
  __int64 v16; // [sp+0h] [bp-68h]@12
  __int64 v17; // [sp+8h] [bp-60h]@15
  __int64 v18; // [sp+10h] [bp-58h]@15
  __int64 v19; // [sp+18h] [bp-50h]@15
  __int64 v20; // [sp+20h] [bp-48h]@15
  __int64 v21; // [sp+28h] [bp-40h]@15
  int v22[14]; // [sp+30h] [bp-38h]@1

  v1 = v22;
  read_six_numbers(a1, (__int64)v22);
  v2 = 0;
  while ( 1 )
  {
    if ( (unsigned int)(*v1 - 1) > 5 )
      explode_bomb(a1, (__int64)v22);
    if ( ++v2 == 6 )
      break;
    v3 = v2;
    do
    {
      if ( *v1 == v22[v3] )
        explode_bomb(a1, (__int64)v22);
      ++v3;
    }
    while ( v3 <= 5 );
    ++v1;
  }
  v4 = 0LL;
  do
  {
    v7 = v22[v4 / 4];
    v6 = 1;
    v5 = &node1;
    if ( v7 > 1 )
    {
      do
      {
        v5 = (_QWORD *)v5[1];
        ++v6;
      }
      while ( v6 != v7 );
    }
    *(__int64 *)((char *)&v16 + 2 * v4) = (__int64)v5;
    v4 += 4LL;
  }
  while ( v4 != 24 );
  v8 = v16;
  v9 = v17;
  *(_QWORD *)(v16 + 8) = v17;
  v10 = v18;
  *(_QWORD *)(v9 + 8) = v18;
  v11 = v19;
  *(_QWORD *)(v10 + 8) = v19;
  v12 = v20;
  *(_QWORD *)(v11 + 8) = v20;
  v13 = v21;
  *(_QWORD *)(v12 + 8) = v21;
  *(_QWORD *)(v13 + 8) = 0LL;
  v14 = 0;
  do
  {
    result = *(_DWORD **)(v8 + 8);
    if ( *(_DWORD *)v8 < *result )
      explode_bomb((__int64)&v16, (__int64)&node1);
    v8 = *(_QWORD *)(v8 + 8);
    ++v14;
  }
  while ( v14 != 5 );
  return result;
}
// 400F30: using guessed type int var_38[14];

//----- (000000000040102B) ----------------------------------------------------
__int64 __fastcall phase_2(__int64 a1)
{
  char *v1; // rbx@3
  signed int v2; // ebp@3
  __int64 result; // rax@4
  int v4; // [sp+0h] [bp-38h]@1
  char v5; // [sp+4h] [bp-34h]@3

  read_six_numbers(a1, (__int64)&v4);
  if ( v4 < 0 )
    explode_bomb(a1, (__int64)&v4);
  v1 = &v5;
  v2 = 1;
  do
  {
    result = (unsigned int)(*((_DWORD *)v1 - 1) + v2);
    if ( *(_DWORD *)v1 != (_DWORD)result )
      explode_bomb(a1, (__int64)&v4);
    ++v2;
    v1 += 4;
  }
  while ( v2 != 6 );
  return result;
}

//----- (000000000040106F) ----------------------------------------------------
signed __int64 __fastcall phase_5(_BYTE *a1, __int64 a2)
{
  _BYTE *v2; // rbx@1
  __int64 *v3; // rax@3
  signed __int64 result; // rax@5
  __int64 v5; // [sp+0h] [bp-18h]@3

  v2 = a1;
  if ( (unsigned int)string_length(a1) != 6 )
    explode_bomb((__int64)a1, a2);
  v3 = &v5;
  do
  {
    *(_BYTE *)v3 = array_3327[*v2++ & 0xF];
    v3 = (__int64 *)((char *)v3 + 1);
  }
  while ( v2 != a1 + 6 );
  BYTE6(v5) = 0;
  result = strings_not_equal(&v5, "flyers");
  if ( (_DWORD)result )
    explode_bomb((__int64)&v5, (__int64)"flyers");
  return result;
}

//----- (00000000004010CD) ----------------------------------------------------
signed __int64 __fastcall phase_1(_BYTE *a1)
{
  signed __int64 result; // rax@1

  result = strings_not_equal(a1, "The future will be better tomorrow.");
  if ( (_DWORD)result )
    explode_bomb((__int64)a1, (__int64)"The future will be better tomorrow.");
  return result;
}

//----- (00000000004010E9) ----------------------------------------------------
__int64 __fastcall phase_4(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5)
{
  __int64 v5; // rdi@5
  __int64 result; // rax@5
  int v7; // [sp+8h] [bp-10h]@1
  unsigned int v8; // [sp+Ch] [bp-Ch]@1

  if ( __isoc99_sscanf(a1, "%d %d", &v8, &v7, a5) != 2 || (v8 & 0x80000000) != 0 || (signed int)v8 > 14 )
    explode_bomb(a1, (__int64)"%d %d");
  v5 = v8;
  result = func4(v8, 0LL, 14);
  if ( (_DWORD)result != 11 || v7 != 11 )
    explode_bomb(v5, 0LL);
  return result;
}
// 400AC8: using guessed type int __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000401146) ----------------------------------------------------
signed __int64 __fastcall phase_3(__int64 a1)
{
  signed __int64 result; // rax@4
  char v2; // [sp+7h] [bp-11h]@1
  int v3; // [sp+8h] [bp-10h]@1
  int v4; // [sp+Ch] [bp-Ch]@1

  if ( __isoc99_sscanf(a1, "%d %c %d", &v4, &v2, &v3) <= 2 )
    explode_bomb(a1, (__int64)"%d %c %d");
  switch ( v4 )
  {
    case 0:
      result = 104LL;
      if ( v3 != 308 )
        explode_bomb(a1, (__int64)"%d %c %d");
      break;
    case 1:
      result = 112LL;
      if ( v3 != 898 )
        explode_bomb(a1, (__int64)"%d %c %d");
      break;
    case 2:
      if ( v3 != 680 )
        explode_bomb(a1, (__int64)"%d %c %d");
      goto LABEL_21;
    case 3:
      result = 116LL;
      if ( v3 != 703 )
        explode_bomb(a1, (__int64)"%d %c %d");
      return result;
    case 4:
      if ( v3 != 860 )
        explode_bomb(a1, (__int64)"%d %c %d");
LABEL_21:
      result = 107LL;
      break;
    case 5:
      result = 113LL;
      if ( v3 != 344 )
        explode_bomb(a1, (__int64)"%d %c %d");
      return result;
    case 6:
      result = 122LL;
      if ( v3 != 182 )
        explode_bomb(a1, (__int64)"%d %c %d");
      return result;
    case 7:
      result = 99LL;
      if ( v3 != 233 )
        explode_bomb(a1, (__int64)"%d %c %d");
      return result;
    default:
      explode_bomb(a1, (__int64)"%d %c %d");
      return result;
  }
  if ( (_BYTE)result != v2 )
    explode_bomb(a1, (__int64)"%d %c %d");
  return result;
}
// 400AC8: using guessed type int __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000401290) ----------------------------------------------------
__int64 __fastcall string_length(_BYTE *a1)
{
  _BYTE *v1; // rdx@1
  __int64 result; // rax@1

  v1 = a1;
  for ( result = 0LL; *v1; result = (unsigned int)((_DWORD)v1 - (_DWORD)a1) )
    ++v1;
  return result;
}

//----- (00000000004012AC) ----------------------------------------------------
signed __int64 __fastcall strings_not_equal(_BYTE *a1, _BYTE *a2)
{
  _BYTE *v2; // rbx@1
  int v3; // er12@1
  _BYTE *v4; // rax@3

  v2 = a1;
  v3 = string_length(a1);
  if ( v3 != (unsigned int)string_length(a2) )
    return 1LL;
  if ( *a1 )
  {
    v4 = a2;
    if ( *a1 != *a2 )
      return 1LL;
    while ( *++v2 )
    {
      if ( *v2 != *++v4 )
        return 1LL;
    }
  }
  return 0LL;
}

//----- (0000000000401304) ----------------------------------------------------
void __fastcall __noreturn invalid_phase(__int64 a1)
{
  printf("Invalid phase%s\n", a1);
  exit(8);
}

//----- (0000000000401324) ----------------------------------------------------
__int64 __fastcall send_msg(__int64 a1, __int64 a2)
{
  __int64 result; // rax@4
  __int64 v3; // [sp+0h] [bp-4008h]@4
  char s; // [sp+2000h] [bp-2008h]@4

  if ( strlen((const char *)(16 * (5LL * num_input_strings - 5) + 6306048)) + 100 > 0x2000 )
  {
    printf("ERROR: Input string is too large.", a2);
    exit(8);
  }
  sprintf(&s, "%d:%s:%d:%s", (unsigned int)bomb_id);
  result = driver_post(userid, (__int64)user_password, (__int64)&s, 0, (__int64)&v3);
  if ( (signed int)result < 0 )
  {
    puts((const char *)&v3);
    exit(0);
  }
  return result;
}
// 603250: using guessed type int bomb_id;
// 6038E8: using guessed type int num_input_strings;

//----- (00000000004013E6) ----------------------------------------------------
int __fastcall phase_defused(__int64 a1, __int64 a2)
{
  int result; // eax@1
  char v3; // [sp+8h] [bp-60h]@2
  char v4; // [sp+Ch] [bp-5Ch]@2
  char v5; // [sp+10h] [bp-58h]@2

  result = send_msg(1LL, a2);
  if ( num_input_strings == 6 )
  {
    if ( __isoc99_sscanf(&unk_6039F0, "%d %d %s", &v4, &v3, &v5) == 3 && !(unsigned int)strings_not_equal(&v5, "DrEvil") )
    {
      puts("Curses, you've found the secret phase!");
      puts("But finding it and solving it are quite different...");
      secret_phase((__int64)"But finding it and solving it are quite different...", (__int64)"DrEvil");
    }
    puts("Congratulations! You've defused the bomb!");
    result = puts("Your instructor has been notified and will verify your solution.");
  }
  return result;
}
// 400AC8: using guessed type int __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 6038E8: using guessed type int num_input_strings;

//----- (000000000040146F) ----------------------------------------------------
void __fastcall __noreturn explode_bomb(__int64 a1, __int64 a2)
{
  puts("\nBOOM!!!");
  puts("The bomb has blown up.");
  send_msg(0LL, a2);
  puts("Your instructor has been notified.");
  exit(8);
}

//----- (00000000004014A5) ----------------------------------------------------
int __fastcall read_six_numbers(__int64 a1, __int64 a2)
{
  int result; // eax@1

  result = __isoc99_sscanf(a1, &unk_40250E, a2, a2 + 4, a2 + 8);
  if ( result <= 5 )
    explode_bomb(a1, (__int64)&unk_40250E);
  return result;
}
// 400AC8: using guessed type int __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000004014E7) ----------------------------------------------------
signed __int64 __fastcall blank_line(char *a1)
{
  char *i; // rbp@1
  char v3; // bl@2

  for ( i = a1; *i; ++i )
  {
    v3 = *i;
    if ( !(HIBYTE((*__ctype_b_loc())[v3]) & 0x20) )
      return 0LL;
  }
  return 1LL;
}

//----- (0000000000401524) ----------------------------------------------------
char *skip()
{
  char *v0; // rax@1
  char *v1; // rbx@1

  do
  {
    v0 = fgets((char *)(80LL * num_input_strings + 6306048), 80, infile);
    v1 = v0;
  }
  while ( v0 && (unsigned int)blank_line(v0) );
  return v1;
}
// 6038E8: using guessed type int num_input_strings;

//----- (0000000000401565) ----------------------------------------------------
char *__fastcall read_line(__int64 a1, __int64 a2)
{
  unsigned __int64 v2; // kr08_8@10
  int v3; // eax@12
  char *v4; // rax@12
  int v5; // eax@13
  signed __int64 v6; // rsi@13

  if ( !skip() )
  {
    if ( infile == (FILE *)stdin )
    {
      puts("Error: Premature EOF on stdin");
      exit(8);
    }
    if ( getenv("GRADE_BOMB") )
      exit(0);
    infile = (FILE *)stdin;
    if ( !skip() )
    {
      puts("Error: Premature EOF on stdin");
      exit(0);
    }
  }
  v2 = strlen(&input_strings[80 * num_input_strings]) + 1;
  if ( (signed int)v2 - 1 > 78 )
  {
    puts("Error: Input line too long");
    v3 = num_input_strings++;
    v4 = &input_strings[80 * v3];
    *(_DWORD *)v4 = 1948920362;
    *((_DWORD *)v4 + 1) = 1668183410;
    *((_DWORD *)v4 + 2) = 1684370529;
    *((_DWORD *)v4 + 3) = 2763306;
    explode_bomb((__int64)"Error: Input line too long", a2);
  }
  v5 = num_input_strings;
  v6 = 80LL * num_input_strings;
  *(&input_strings[(_DWORD)v2 - 2] + v6) = 0;
  num_input_strings = v5 + 1;
  return &input_strings[v6];
}
// 6038C0: using guessed type __int64 stdin;
// 6038E8: using guessed type int num_input_strings;

//----- (00000000004016A0) ----------------------------------------------------
__int64 initialize_bomb()
{
  const char *v0; // rdi@2
  const char **v1; // rbx@2
  __int64 result; // rax@9
  __int64 v3; // [sp+0h] [bp-2058h]@9
  char name; // [sp+2000h] [bp-58h]@1

  signal(2, (__sighandler_t)sig_handler);
  if ( gethostname(&name, 0x40uLL) )
  {
    puts("Initialization error: Running on an illegal host [1]");
    exit(8);
  }
  v0 = host_table;
  v1 = (const char **)&unk_6034C8;
  if ( !host_table )
  {
LABEL_12:
    puts("Initialization error: Running on an illegal host [2]");
    exit(8);
  }
  while ( strcasecmp(v0, &name) )
  {
    v0 = *v1;
    ++v1;
    if ( !v0 )
      goto LABEL_12;
  }
  result = init_driver((char *)&v3);
  if ( (signed int)result < 0 )
  {
    printf("Initialization error:\n%s\n", &v3);
    exit(8);
  }
  return result;
}

//----- (000000000040175D) ----------------------------------------------------
void __noreturn sig_handler()
{
  puts("So you think you can stop the bomb with ctrl-c, do you?");
  sleep(3u);
  printf("Well...");
  fflush(stdout);
  sleep(1u);
  puts("OK. :-)");
  exit(16);
}

//----- (00000000004017B0) ----------------------------------------------------
__int64 __fastcall init_driver(char *s)
{
  int v1; // ebp@1
  __int64 result; // rax@2
  struct hostent *v3; // rax@3
  __int64 dest; // [sp+0h] [bp-28h]@5
  __int64 v5; // [sp+8h] [bp-20h]@5

  signal(13, (__sighandler_t)1);
  signal(29, (__sighandler_t)1);
  signal(29, (__sighandler_t)1);
  v1 = socket(2, 1, 0);
  if ( v1 >= 0 )
  {
    v3 = gethostbyname("u2");
    if ( v3 )
    {
      dest = 0LL;
      v5 = 0LL;
      LOWORD(dest) = 2;
      bcopy(*(const void **)v3->h_addr_list, (char *)&dest + 4, v3->h_length);
      WORD1(dest) = 28219;
      if ( connect(v1, (const struct sockaddr *)&dest, 0x10u) >= 0 )
      {
        close(v1);
        *(_WORD *)s = 19279;
        s[2] = 0;
        result = 0LL;
      }
      else
      {
        sprintf(s, "Error: Unable to connect to server %s", "u2", dest);
        close(v1);
        result = 0xFFFFFFFFLL;
      }
    }
    else
    {
      *(_DWORD *)s = 1869771333;
      *((_DWORD *)s + 1) = 1142962802;
      *((_DWORD *)s + 2) = 1763726158;
      *((_DWORD *)s + 3) = 1853169779;
      *((_DWORD *)s + 4) = 1701601889;
      *((_DWORD *)s + 5) = 544175136;
      *((_DWORD *)s + 6) = 1869833586;
      *((_DWORD *)s + 7) = 543520364;
      *((_DWORD *)s + 8) = 1987208563;
      *((_DWORD *)s + 9) = 1629516389;
      *((_DWORD *)s + 10) = 1701995620;
      *((_WORD *)s + 22) = 29555;
      s[46] = 0;
      close(v1);
      result = 0xFFFFFFFFLL;
    }
  }
  else
  {
    *(_DWORD *)s = 1869771333;
    *((_DWORD *)s + 1) = 1126185586;
    *((_DWORD *)s + 2) = 1852139884;
    *((_DWORD *)s + 3) = 1853169780;
    *((_DWORD *)s + 4) = 1701601889;
    *((_DWORD *)s + 5) = 544175136;
    *((_DWORD *)s + 6) = 1634038371;
    *((_DWORD *)s + 7) = 1931502964;
    *((_DWORD *)s + 8) = 1701536623;
    *((_WORD *)s + 18) = 116;
    result = 0xFFFFFFFFLL;
  }
  return result;
}

//----- (0000000000401985) ----------------------------------------------------
unsigned int __fastcall init_timeout(unsigned int seconds)
{
  unsigned int v1; // ebx@1
  unsigned int v2; // edi@2
  unsigned int result; // eax@4

  v1 = seconds;
  if ( seconds )
  {
    signal(14, (__sighandler_t)sigalrm_handler);
    v2 = 0;
    if ( (v1 & 0x80000000) == 0 )
      v2 = v1;
    result = alarm(v2);
  }
  return result;
}

//----- (00000000004019AC) ----------------------------------------------------
signed __int64 __fastcall rio_readlineb(__int64 a1, _BYTE *a2, unsigned __int64 a3)
{
  _BYTE *v3; // r15@1
  signed int v4; // er14@2
  int v5; // eax@3
  signed int v6; // edx@5
  int v7; // ebp@8
  signed int v8; // ecx@13
  signed __int64 result; // rax@14
  unsigned __int64 v10; // [sp+0h] [bp-58h]@1
  char dest; // [sp+1Fh] [bp-39h]@10

  v10 = a3;
  v3 = a2;
  if ( a3 <= 1 )
  {
    v4 = 1;
LABEL_20:
    *v3 = 0;
    return v4;
  }
  v4 = 1;
  while ( 1 )
  {
    while ( 1 )
    {
      v7 = *(_DWORD *)(a1 + 4);
      if ( v7 > 0 )
        break;
      v5 = read(*(_DWORD *)a1, (void *)(a1 + 16), 0x2000uLL);
      *(_DWORD *)(a1 + 4) = v5;
      if ( v5 >= 0 )
      {
        if ( !v5 )
        {
          v6 = 0;
          goto LABEL_23;
        }
        *(_QWORD *)(a1 + 8) = a1 + 16;
      }
      else if ( *__errno_location() != 4 )
      {
        v6 = -1;
LABEL_23:
        v8 = v4;
        goto LABEL_14;
      }
    }
    if ( !v7 )
      break;
    dest = *(_BYTE *)(*(_QWORD *)(a1 + 8))++;
    --*(_DWORD *)(a1 + 4);
    *v3++ = dest;
    if ( dest != 10 && ++v4 < v10 )
      continue;
    goto LABEL_20;
  }
  memcpy(&dest, *(const void **)(a1 + 8), 0LL);
  *(_QWORD *)(a1 + 8) = *(_QWORD *)(a1 + 8);
  *(_DWORD *)(a1 + 4) = *(_DWORD *)(a1 + 4);
  v6 = 0;
  v8 = v4;
LABEL_14:
  result = -1LL;
  if ( !v6 )
  {
    result = 0LL;
    if ( v8 != 1 )
      goto LABEL_20;
  }
  return result;
}

//----- (0000000000401ACA) ----------------------------------------------------
__int64 __usercall submitr@<rax>(char *name@<rdi>, _BYTE *a2@<rdx>, const char *a3@<rcx>, __int16 a4@<si>, __int64 a5@<r8>, _BYTE *a6@<r9>, __int64 a7, __int64 a8)
{
  _BYTE *v8; // r15@1
  int v9; // er13@1
  __int64 result; // rax@2
  struct hostent *v11; // rax@3
  __int16 v12; // bp@5
  unsigned __int64 v13; // rbx@7
  _BYTE *v14; // rdi@7
  signed __int64 v15; // rcx@7
  bool v16; // zf@9
  signed __int64 v17; // rsi@10
  unsigned __int64 v18; // rbp@10
  _BYTE *v19; // rdi@10
  signed __int64 v20; // rcx@10
  unsigned __int64 v21; // kr08_8@15
  char *v22; // rbx@16
  char *v23; // rbp@16
  int i; // er12@16
  char v25; // al@17
  char *k; // rbp@33
  ssize_t v27; // rax@34
  size_t v28; // rbx@37
  __int64 v29; // rdi@39
  char *v30; // rsi@39
  unsigned int v31; // eax@39
  __int64 l; // rcx@43
  signed __int64 v33; // rdx@46
  __int64 v34; // rdi@61
  char *v35; // rsi@61
  unsigned int v36; // eax@61
  __int64 j; // rcx@65
  signed __int64 v38; // rdx@68
  unsigned __int64 v39; // rcx@78
  signed __int64 v40; // r12@78
  _BYTE *v41; // [sp+18h] [bp-A090h]@1
  const char *v42; // [sp+20h] [bp-A088h]@1
  __int64 v43; // [sp+28h] [bp-A080h]@1
  char s; // [sp+30h] [bp-A078h]@29
  char v45; // [sp+31h] [bp-A077h]@29
  char v46; // [sp+32h] [bp-A076h]@29
  char v47; // [sp+40h] [bp-A068h]@53
  unsigned int v48; // [sp+204Ch] [bp-805Ch]@1
  char v49; // [sp+2050h] [bp-8058h]@53
  char v50; // [sp+4050h] [bp-6058h]@15
  char v51; // [sp+6050h] [bp-4058h]@51
  char v52; // [sp+6051h] [bp-4057h]@58
  char v53; // [sp+6052h] [bp-4056h]@59
  int v54; // [sp+8050h] [bp-2058h]@51
  int v55; // [sp+8054h] [bp-2054h]@51
  __int64 *v56; // [sp+8058h] [bp-2050h]@51
  __int64 v57; // [sp+8060h] [bp-2048h]@51
  struct sockaddr addr; // [sp+A060h] [bp-48h]@5

  v41 = a2;
  v42 = a3;
  v43 = a5;
  v8 = a6;
  v48 = 0;
  v9 = socket(2, 1, 0);
  if ( v9 < 0 )
  {
    qmemcpy((void *)a8, "Error: Client unable to create socket", 0x26uLL);
    return 0xFFFFFFFFLL;
  }
  v11 = gethostbyname(name);
  if ( !v11 )
  {
    qmemcpy((void *)a8, "Error: DNS is unable to resolve server address", 0x2FuLL);
    close(v9);
    return 0xFFFFFFFFLL;
  }
  *(_QWORD *)&addr.sa_family = 0LL;
  *(_QWORD *)&addr.sa_data[6] = 0LL;
  addr.sa_family = 2;
  bcopy(*(const void **)v11->h_addr_list, &addr.sa_data[2], v11->h_length);
  v12 = __ROR2__(a4, 8);
  *(_WORD *)&addr.sa_data[0] = v12;
  if ( connect(v9, &addr, 0x10u) < 0 )
  {
    qmemcpy((void *)a8, "Error: Unable to connect to the server", 0x27uLL);
    close(v9);
    return 0xFFFFFFFFLL;
  }
  v13 = strlen((const char *)a7) + 1;
  v14 = v41;
  v15 = -1LL;
  do
  {
    if ( !v15 )
      break;
    v16 = *v14++ == 0;
    --v15;
  }
  while ( !v16 );
  v17 = v15;
  v18 = strlen(v42) + 1;
  v19 = v8;
  v20 = -1LL;
  do
  {
    if ( !v20 )
      break;
    v16 = *v19++ == 0;
    --v20;
  }
  while ( !v16 );
  if ( v18 - v17 - v20 + 3 * v13 - 3 + 123 > 0x2000 )
  {
    *(_DWORD *)a8 = 1869771333;
    *(_DWORD *)(a8 + 4) = 1377843826;
    *(_DWORD *)(a8 + 8) = 1819636581;
    *(_DWORD *)(a8 + 12) = 1953702004;
    *(_DWORD *)(a8 + 16) = 1735289202;
    *(_DWORD *)(a8 + 20) = 1869575200;
    *(_DWORD *)(a8 + 24) = 1918987296;
    *(_DWORD *)(a8 + 28) = 539911527;
    *(_DWORD *)(a8 + 32) = 1919118921;
    *(_DWORD *)(a8 + 36) = 1702060389;
    *(_DWORD *)(a8 + 40) = 1112888096;
    *(_DWORD *)(a8 + 44) = 1381255501;
    *(_DWORD *)(a8 + 48) = 1480674655;
    *(_DWORD *)(a8 + 52) = 4609346;
    close(v9);
    return 0xFFFFFFFFLL;
  }
  memset(&v50, 0, 0x2000uLL);
  v21 = strlen((const char *)a7) + 1;
  if ( (_DWORD)v21 != 1 )
  {
    v22 = &v50;
    v23 = (char *)a7;
    for ( i = v21 - 2; ; --i )
    {
      v25 = *v23;
      if ( *v23 != 42
        && v25 != 45
        && v25 != 46
        && v25 != 95
        && (unsigned __int8)(v25 - 48) > 9u
        && (unsigned __int8)(v25 - 65) > 0x19u
        && (unsigned __int8)(v25 - 97) > 0x19u )
      {
        if ( v25 == 32 )
        {
          *v22++ = 43;
        }
        else
        {
          if ( (unsigned __int8)(v25 - 32) > 0x5Fu && v25 != 9 )
          {
            qmemcpy((void *)a8, "Error: Result string contains an illegal or unprintable character.", 0x43uLL);
            close(v9);
            return 0xFFFFFFFFLL;
          }
          sprintf(&s, "%%%02X", (unsigned __int8)v25);
          *v22 = s;
          v22[1] = v45;
          v22[2] = v46;
          v22 += 3;
        }
      }
      else
      {
        *v22++ = v25;
      }
      if ( !i )
        break;
      ++v23;
    }
  }
  sprintf(
    &v51,
    "GET /%s/submitr.pl/?userid=%s&userpwd=%s&lab=%s&result=%s&submit=submit HTTP/1.0\r\n\r\n",
    v41,
    v42,
    v43,
    v8,
    &v50);
  v39 = strlen(&v51) + 1;
  v40 = v39 - 1;
  if ( v39 == 1 )
  {
LABEL_51:
    v54 = v9;
    v55 = 0;
    v56 = &v57;
    if ( rio_readlineb((__int64)&v54, &v51, 0x2000uLL) > 0 )
    {
      __isoc99_sscanf(&v51, "%s %d %[a-zA-z ]", &v49, &v48, &v47);
      if ( v48 == 200 )
      {
        while ( v51 != asc_402780[0] || v52 != asc_402780[1] || v53 != asc_402780[2] )
        {
          if ( rio_readlineb((__int64)&v54, &v51, 0x2000uLL) <= 0 )
          {
            *(_DWORD *)a8 = 1869771333;
            *(_DWORD *)(a8 + 4) = 1126185586;
            *(_DWORD *)(a8 + 8) = 1852139884;
            *(_DWORD *)(a8 + 12) = 1853169780;
            *(_DWORD *)(a8 + 16) = 1701601889;
            *(_DWORD *)(a8 + 20) = 544175136;
            *(_DWORD *)(a8 + 24) = 1684104562;
            *(_DWORD *)(a8 + 28) = 1634035744;
            *(_DWORD *)(a8 + 32) = 1936876900;
            *(_DWORD *)(a8 + 36) = 1869768224;
            *(_DWORD *)(a8 + 40) = 1702043757;
            *(_DWORD *)(a8 + 44) = 1919252082;
            *(_BYTE *)(a8 + 48) = 0;
            close(v9);
            return 0xFFFFFFFFLL;
          }
        }
        if ( rio_readlineb((__int64)&v54, &v51, 0x2000uLL) > 0 )
        {
          strcpy((char *)a8, &v51);
          close(v9);
          if ( *(_BYTE *)a8 != aOk[0] || __PAIR__(*(_BYTE *)(a8 + 2), *(_BYTE *)(a8 + 1)) != __PAIR__(aOk[2], aOk[1]) )
            result = 0xFFFFFFFFLL;
          else
            result = 0LL;
        }
        else
        {
          v34 = a8;
          v35 = "Error: Client unable to read status message from server";
          v36 = 56;
          if ( a8 & 1 )
          {
            *(_BYTE *)a8 = aErrorClientU_2[0];
            v35 = "rror: Client unable to read status message from server";
            v34 = a8 + 1;
            v36 = 55;
          }
          if ( v34 & 2 )
          {
            *(_WORD *)v34 = *(_WORD *)v35;
            v35 += 2;
            v34 += 2LL;
            v36 -= 2;
          }
          for ( j = v36 >> 2; j; --j )
          {
            *(_DWORD *)v34 = *(_DWORD *)v35;
            v35 += 4;
            v34 += 4LL;
          }
          v38 = 0LL;
          if ( v36 & 2 )
          {
            *(_WORD *)v34 = *(_WORD *)v35;
            v38 = 2LL;
          }
          if ( v36 & 1 )
            *(_BYTE *)(v34 + v38) = v35[v38];
          close(v9);
          result = 0xFFFFFFFFLL;
        }
      }
      else
      {
        sprintf((char *)a8, "Error: HTTP request failed with error %d: %s", v48);
        close(v9);
        result = 0xFFFFFFFFLL;
      }
    }
    else
    {
      qmemcpy((void *)a8, "Error: Client unable to read first header from server", 0x36uLL);
      close(v9);
      result = 0xFFFFFFFFLL;
    }
  }
  else
  {
    v28 = v39 - 1;
    for ( k = &v51; ; k += v27 )
    {
      v27 = write(v9, k, v28);
      if ( v27 <= 0 )
      {
        if ( *__errno_location() != 4 )
          goto LABEL_39;
        v27 = 0LL;
      }
      v28 -= v27;
      if ( !v28 )
        break;
    }
    if ( v40 >= 0 )
      goto LABEL_51;
LABEL_39:
    v29 = a8;
    v30 = "Error: Client unable to write to the server";
    v31 = 44;
    if ( a8 & 1 )
    {
      *(_BYTE *)a8 = aErrorClientU_0[0];
      v30 = "rror: Client unable to write to the server";
      v29 = a8 + 1;
      v31 = 43;
    }
    if ( v29 & 2 )
    {
      *(_WORD *)v29 = *(_WORD *)v30;
      v30 += 2;
      v29 += 2LL;
      v31 -= 2;
    }
    for ( l = v31 >> 2; l; --l )
    {
      *(_DWORD *)v29 = *(_DWORD *)v30;
      v30 += 4;
      v29 += 4LL;
    }
    v33 = 0LL;
    if ( v31 & 2 )
    {
      *(_WORD *)v29 = *(_WORD *)v30;
      v33 = 2LL;
    }
    if ( v31 & 1 )
      *(_BYTE *)(v29 + v33) = v30[v33];
    close(v9);
    result = 0xFFFFFFFFLL;
  }
  return result;
}
// 400AC8: using guessed type int __fastcall __isoc99_sscanf(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000040210C) ----------------------------------------------------
__int64 __fastcall driver_post(const char *a1, __int64 a2, __int64 a3, int a4, __int64 a5)
{
  __int64 v5; // rbx@1
  __int64 result; // rax@2

  v5 = a5;
  if ( a4 )
  {
    printf("\nAUTORESULT_STRING=%s\n", a3);
    *(_WORD *)v5 = 19279;
    *(_BYTE *)(v5 + 2) = 0;
    result = 0LL;
  }
  else if ( a1 && *a1 )
  {
    result = submitr("u2", "csapp", a1, 15214, a2, "89230_5777_ex4", a3, a5);
  }
  else
  {
    *(_WORD *)a5 = 19279;
    *(_BYTE *)(a5 + 2) = 0;
    result = 0LL;
  }
  return result;
}

//----- (0000000000402183) ----------------------------------------------------
void __noreturn sigalrm_handler()
{
  fprintf(stderr, "Program timed out after %d seconds\n", 0LL);
  exit(1);
}

//----- (00000000004021C0) ----------------------------------------------------
void _libc_csu_init(void)
{
  init_proc();
}

//----- (0000000000402250) ----------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
  void (*result)(void); // rax@1
  void (**v1)(void); // rbx@2

  result = (void (*)(void))_CTOR_LIST__;
  if ( _CTOR_LIST__ != -1 )
  {
    v1 = (void (**)(void))&_CTOR_LIST__;
    do
    {
      --v1;
      result();
      result = *v1;
    }
    while ( *v1 != (void (*)(void))-1 );
  }
  return result;
}
// 602F88: using guessed type __int64 _CTOR_LIST__;

//----- (0000000000402288) ----------------------------------------------------
void term_proc()
{
  _do_global_dtors_aux();
}

#error "There were 1 decompilation failure(s) on 36 function(s)"
